Fix outdated column names for preparedata scripts
phbasler/BSMPT pull request #166
Opened 2024-09-04 13:20 UTC by lisabiermann

This PR unifies all `prepareData` scripts and updates them to use the column name convention of the latest public `ScannerS`. It also adds a `README`.

2024-11-29 18:19 UTC, vollous requested changes
This PR has conflicts with changes made by Phillip already implemented in the develop branch. Can you take a look?

2025-03-27 19:49 UTC, phbasler commented
@lisabiermann  @vollous  I applied black to the files which reduced the merge conflicts

2025-04-15 07:36 UTC, lisabiermann commented
There is no merge conflict any more with the develop branch, so we could merge it if you approve.

2025-04-15 20:24 UTC, phbasler approved these changes

2025-04-15 21:01 UTC, merged