BSMPT v3.0.7 pull request
phbasler/BSMPT pull request #180
Opened 2024-11-28 15:54 UTC by vollous

### Change log
- Small changes to ```prepareData_*.py``` scripts.
- Changes to the ```python``` model implementation method.

2025-04-10 18:43 UTC, phbasler commented
We need to adjust the version for the pr

2025-04-12 17:54 UTC, phbasler requested changes

2025-04-12 17:54 UTC, phbasler commented on README.md
> +2. At `tools/ModelGeneration/Mathematica` we provide a Mathematica framework to implement your model.
Any reason why you made it as number 2? 
We could try to reorder them in a way that the numbering represents the recommend method.

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  int which_transition_temp = false;
```suggestion
  int which_transition_temp = 0;
```

I find this highly irritating. Why write false here and convert it to 0?
Also why not use an enum class with these values?

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +   * @brief Gstar spline, T > 214.0
Where does the cutoff of 214 GeV come from?

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  void SetAndCalculateGWParameters(const int &which_transition_temp_in);
Calling this function with an enum makes it more readable

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +                 const int &UserDefined_PNLO_scaling_in,
Why insert the new argument in the middle?
I would recommend inserting it at the end. That way users can just extend there call and not have to reorder their arguments.

Technically you would also need a default value for this (at the end), so that old implementations dont break. Otherwise we have a major break in the API and would need to raise the version to 4.0

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +                 const int &UserDefined_PNLO_scaling_in,
same as above

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  double GetGstar(const double &T) const;
Maybe a default value or an overload for old calls?

2025-04-12 17:54 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  void CalcTransitionTemp();
Why removed the argument?

2025-04-12 18:25 UTC, phbasler requested changes

2025-04-12 18:25 UTC, phbasler commented on sh/prepareData_R2HDM.py
I think something went wrong with these scripts.
The R2HDM script has two convert functions

2025-04-12 18:25 UTC, phbasler commented on sh/prepareData_R2HDM.py
>          df = pd.read_csv(file, index_col=HasIndexCol, sep=Separator)
Why is this indented?

2025-04-12 18:25 UTC, phbasler commented on sh/prepareData_C2HDM.py
> +    re_m12squared='re_m12sq'
This does not work.
Executing black on this file yields errors.
All variables are defined twice, sometimes with different values.

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +  for (auto m : phase_pair.false_phase.MinimumPhaseVector)
```suggestion
  for (const auto& m : phase_pair.false_phase.MinimumPhaseVector)
```

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +  for (auto m : phase_pair.true_phase.MinimumPhaseVector)
```suggestion
  for (const auto& m : phase_pair.true_phase.MinimumPhaseVector)
```

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +    V_list.push_back(m.potential);
Isnt this the same code for false_phase and true_phase? Maybe make a function with the phase as an arugment and call that?

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +  const double TTreshold = TGstarLowT.back(); // = TGstarHighT.front()
Why the comment with .front?

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +      ss << "\n\033[1;93mWARNING: Detected wall velocity outside detonation "
What is with the \033[1;93m ?

2025-04-12 18:25 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +  if (isnan(cs))
Is this ok for you that this case is not triggered by some tests?

2025-04-12 18:25 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +    data.XiShock = 1.; // Does not matter as efficiency if zero
```suggestion
  if (data.kappa_sw > 0)
    {
      data.XiShock = vprofile.back().front();
    }
  else
    {
      data.XiShock = 1.; // Does not matter as efficiency if zero
     }
```

Just to match the style of the rest of the code

2025-04-12 18:25 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +double GetHtauSH(const double HR, const double K_sw)
What should happen for K_sw < 0 as an input?

2025-04-12 18:25 UTC, phbasler commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
This does not match the documentation.
There you say 

f [0..1] set
   * to value, for -1 we use the upper bound from
   * https://arxiv.org/abs/1704.05871

So shouldnt the if check match this?

2025-04-12 18:25 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +  if (gamma_eq < 1) return 0.; // dV - P_LO < P_NLO. Unphysical gamma < 1;
What is with the commented code?
```suggestion
  if (gamma_eq < 1) return 0.; 
```

2025-04-12 19:36 UTC, phbasler requested changes

2025-04-12 19:36 UTC, phbasler commented on src/transition_tracer/transition_tracer.cpp
> +                input, new_transition_data.crit_false_vev, pair.crit_temp);
Why do you need these function calls?

2025-04-12 19:36 UTC, phbasler commented on tools/ModelGeneration/Mathematica/R2HDM.m
Just as a remark: I don't have mathematica, so I cant review these files properly

2025-04-12 19:36 UTC, phbasler commented on tests/unittests/Test-origin.cpp
> +TEST_CASE("Check CheckImplementation", "[origin]")
Isn't this the same test as `TEST_CASE("Run CheckImplementation in c2hdm", "[c2hdm]")` in Test-c2hdm? 
I added it with my conan PR, so we probably did the same thing here

2025-04-12 19:36 UTC, phbasler commented on tests/unittests/Test-gw.cpp
> +  REQUIRE(kappaNuMuModel(0.5106836025229592,
You call the function here many times with different paramters, correct?
This looks like a job for parameterised tests https://github.com/catchorg/Catch2/blob/devel/docs/generators.md

2025-04-14 06:59 UTC, lisabiermann commented on README.md
> +2. At `tools/ModelGeneration/Mathematica` we provide a Mathematica framework to implement your model.
No reason, I reordered them as 1. `python`, 2. `Mathematica`, 3. `Maple` (from open to closed source, most to least widely used).

2025-04-14 07:08 UTC, lisabiermann commented on src/transition_tracer/transition_tracer.cpp
> +                input, new_transition_data.crit_false_vev, pair.crit_temp);
The `CheckMassRatio` function prints the values of `m^2/T^2`, coloured by how large the ratio is, and returns the maximal ratio. The latter we use in `Test-gw.cpp` to test this function, the former is to give at least some information about the validity of the high-T expansion.

2025-04-14 07:09 UTC, lisabiermann commented on src/transition_tracer/transition_tracer.cpp
> +                input, new_transition_data.crit_false_vev, pair.crit_temp);
We call it for each characteristic temperature that we calculate.

2025-04-14 07:18 UTC, lisabiermann commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
This part has changed in the updated manual, we now use the upper bound $\epsilon = \sqrt{1 - \Upsilon}$, see Eq. (3.83) and Eq. (3.77) for the definition of $\Upsilon$.

2025-04-14 07:19 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +   * @brief Gstar spline, T > 214.0
It is the QCD phase transition. https://arxiv.org/pdf/1609.04979

2025-04-14 07:54 UTC, lisabiermann commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  double GetGstar(const double &T) const;
We added an overload for the call with no argument with `CalcGstarPureRad` (effective degrees of freedom in the fully thermalized universe). This way, `GetGstar()` returns the same value as before, and `GetGstar(T)` gives the new temperature-dependent value.

2025-04-14 09:17 UTC, phbasler commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
Then the documentation has to be adjusted. They should match

2025-04-14 10:35 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  void SetAndCalculateGWParameters(const int &which_transition_temp_in);
Done

2025-04-14 10:36 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  int which_transition_temp = false;
I made this an enum class

2025-04-14 10:38 UTC, vollous commented on tests/unittests/Test-gw.cpp
> +  REQUIRE(kappaNuMuModel(0.5106836025229592,
But the results were evaluated numerically. Do I save them in a file that gets imported during testing?

2025-04-14 10:49 UTC, lisabiermann commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
What documentation do you refer to?

2025-04-14 11:38 UTC, phbasler commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
The function documentation in the header file. 

https://github.com/phbasler/BSMPT/blob/18e073d7eb90753a5896c91b7f586b2df5622235/include/BSMPT/gravitational_waves/gw.h#L111-L117

2025-04-14 12:27 UTC, lisabiermann commented on sh/prepareData_C2HDM.py
> +    re_m12squared='re_m12sq'
I propose to fix the `sh/prepareData_*.py` files by merging #165. Ok?

2025-04-14 12:27 UTC, lisabiermann commented on sh/prepareData_R2HDM.py
>          df = pd.read_csv(file, index_col=HasIndexCol, sep=Separator)
I propose to fix the `sh/prepareData_*.py` files by merging #165. Ok?

2025-04-14 12:27 UTC, lisabiermann commented on sh/prepareData_R2HDM.py
I propose to fix the `sh/prepareData_*.py` files by merging #165. Ok?

2025-04-14 13:01 UTC, vollous commented on include/BSMPT/bounce_solution/gstar.h
> +extern const std::vector<double> TGstarLowT, TGstarHighT;
Added

2025-04-14 13:21 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +                 const int &UserDefined_PNLO_scaling_in,
No particular reason. Moved to the end and given default value.

2025-04-14 13:21 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +                 const int &UserDefined_PNLO_scaling_in,
Done same as above

2025-04-14 13:22 UTC, vollous commented on include/BSMPT/gravitational_waves/gw.h
> +  double K_sw           = false; // kinetic energy fraction for sound waves
Better clarity and to match the manual

2025-04-14 13:25 UTC, lisabiermann commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
The documentation is updated now.

2025-04-14 13:26 UTC, vollous commented on src/bounce_solution/bounce_solution.cpp
> +  if (isnan(cs))
Yes, Its just that a ```sqrt(x)```is always dangerous and there is no assurence that the argument $x >0$. This is just to be on the safe side.

2025-04-14 13:40 UTC, lisabiermann commented on src/bounce_solution/bounce_solution.cpp
> +      ss << "\n\033[1;93mWARNING: Detected wall velocity outside detonation "
This is to make the warning appear in color, for better visibility (like we do with other output in the code).

2025-04-14 13:42 UTC, vollous commented on tests/unittests/Test-origin.cpp
> +TEST_CASE("Check CheckImplementation", "[origin]")
It is, it was added when we fixed the loop dependency. I will remove this one as it is C2HDM-specific.

2025-04-14 13:51 UTC, vollous commented on tools/ModelGeneration/Mathematica/R2HDM.m
Just tested it and it is working. We also have another PhD student using it and it works quite well.

2025-04-14 14:43 UTC, lisabiermann commented on tools/ModelGeneration/Mathematica/R2HDM.m
I also tested it for the PR to develop of that branch and know at least one person using it successfully.

2025-04-14 20:29 UTC, phbasler requested changes

2025-04-14 20:29 UTC, phbasler commented on src/transition_tracer/transition_tracer.cpp
> +       << ") / T^2 = " << vec_to_string(massOverTempSq) << "\033[0m\n";
```suggestion
       << ") / T^2 = " << massOverTempSq << "\033[0m\n";
```

2025-04-14 20:29 UTC, phbasler commented on src/transition_tracer/transition_tracer.cpp
> +       << ") / T^2 = " << vec_to_string(massOverTempSq) << "\033[0m\n";
```suggestion
       << ") / T^2 = " << massOverTempSq << "\033[0m\n";
```

2025-04-14 20:29 UTC, phbasler commented on src/transition_tracer/transition_tracer.cpp
> +       << ") / T^2 = " << vec_to_string(massOverTempSq) << "\033[0m\n";
```suggestion
       << ") / T^2 = " << massOverTempSq << "\033[0m\n";
```

2025-04-14 20:29 UTC, phbasler commented on include/BSMPT/transition_tracer/transition_tracer.h
> +   * @brief CheckMassRatio
Can you add a description of the function?

2025-04-14 20:29 UTC, phbasler commented on include/BSMPT/gravitational_waves/gw.h
> + * (2=detonation, 1=hybrid, 0=deflagration)
Wouldn't the second part here also be better as an enum class?

2025-04-14 20:29 UTC, phbasler commented on include/BSMPT/gravitational_waves/gw.h
> + * and returns (dξ/dv, dw/dv).
How is the return value an int if it is two derivatives?

2025-04-14 20:29 UTC, phbasler commented on src/bounce_solution/bounce_solution.cpp
> +                     UserDefined_PNLO_scaling_in)
In line 92 you have

`for (auto GroupElement : GroupElements)`

Please change that to `for (const auto& GroupElement : GroupElements)`

2025-04-14 20:29 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +double GetHtauSH(const double HR, const double K_sw)
If you are sure of it, then it is fine

2025-04-14 20:29 UTC, phbasler commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
I don't see an update

2025-04-14 20:29 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +  for (auto massSq : HiggsSq_True)
```suggestion
  for (const auto& massSq : HiggsSq_True)
```

Otherwise you are making a lot of copies

2025-04-14 20:29 UTC, phbasler commented on src/gravitational_waves/gw.cpp
> +  if (gamma_eq < 1) return 0.; // dV - P_LO < P_NLO. Unphysical gamma < 1;
yes, this sounds better

2025-04-14 20:29 UTC, phbasler commented on tests/unittests/Test-gw.cpp
> +  REQUIRE(kappaNuMuModel(0.5106836025229592,
No, from gtest I know this like 

TEST_P()
{
 REQUIRE(kappaNuMuModel(a,b,c,d) == result;
}

P.Instantiate( { values1, values 2 , ... }

This also has the advantage that each number pair is an extra test and you see better which one fails

2025-04-15 07:25 UTC, lisabiermann commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
Hmm.. The commit is [this one](https://github.com/phbasler/BSMPT/pull/180/commits/5eb6961f74698ae2abd883327be63a084d0d5751), I don't know why it's not shown in this conversation.

2025-04-15 07:28 UTC, lisabiermann commented on src/gravitational_waves/gw.cpp
> +  if (gamma_eq < 1) return 0.; // dV - P_LO < P_NLO. Unphysical gamma < 1;
[Done.](https://github.com/phbasler/BSMPT/pull/180/commits/6e023a438c923d346fb7106393dc9d6b78b8026c)

2025-04-15 08:11 UTC, lisabiermann commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  double I(const double &T);
The false vacuum fraction is $\mathrm{e}^{-I(T)}$, we derive it in `BounceSolution::CalcFalseVacFraction`. What about `FalseVacFractionExponent` instead?

2025-04-15 08:16 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +   * @brief Gstar spline, T > 214.0
Sure, I will add it for this and for the other member var.

2025-04-15 08:18 UTC, vollous commented on src/bounce_solution/bounce_solution.cpp
> +  const double TTreshold = TGstarLowT.back(); // = TGstarHighT.front()
Modified this to make it more readable

2025-04-15 08:25 UTC, vollous commented on src/gravitational_waves/gw.cpp
> +  for (auto massSq : HiggsSq_True)
Updated in new branch

2025-04-15 08:28 UTC, vollous commented on src/transition_tracer/transition_tracer.cpp
> +       << ") / T^2 = " << vec_to_string(massOverTempSq) << "\033[0m\n";
Removed in new branch

2025-04-15 08:35 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +                 std::vector<Eigen::MatrixXd> GroupElements_in,
Corrected in new branch

2025-04-15 08:50 UTC, lisabiermann commented on include/BSMPT/transition_tracer/transition_tracer.h
> +   * @brief CheckMassRatio
[Done.](https://github.com/phbasler/BSMPT/pull/180/commits/ecfc32385f01cf1b0441c08f1bf50ffb81615dd4)

2025-04-15 08:59 UTC, vollous commented on tests/unittests/Test-gw.cpp
> +  REQUIRE(kappaNuMuModel(0.5106836025229592,
Done. Take a look to check if that was what you wanted.

2025-04-15 09:59 UTC, vollous commented on include/BSMPT/gravitational_waves/gw.h
> + * and returns (dξ/dv, dw/dv).
Hum, this is the documentation of another function. The `int` here is the detonation mode. This snipped was adapted from another paper.

2025-04-15 13:53 UTC, vollous commented on src/bounce_solution/bounce_solution.cpp
> +                     UserDefined_PNLO_scaling_in)
Done in PR

2025-04-15 14:24 UTC, vollous commented on src/bounce_solution/bounce_solution.cpp
> +    V_list.push_back(m.potential);
Sure, added in PR.

2025-04-15 14:34 UTC, vollous commented on include/BSMPT/gravitational_waves/gw.h
> + * (2=detonation, 1=hybrid, 0=deflagration)
Yes, added in PR

2025-04-15 14:37 UTC, vollous commented on include/BSMPT/gravitational_waves/gw.h
> + * and returns (dξ/dv, dw/dv).
I make this int instead a enum class, as per your suggestion

2025-04-15 20:28 UTC, phbasler commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
You still write 

`If [0..1] set
   * to value, for -1 we use the upper bound sqrt(1 - Upsilon)`

but the code is 
-1 = sqrt()
else: value

So what should happen to an input value of 2? Or -0.2?

2025-04-15 20:33 UTC, phbasler commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  double I(const double &T);
sounds good.
Otherwise if you think just I(T) is the most readable then we can keep it that way, but I prefer `FalseVacFractionExponent_I`

2025-04-15 20:36 UTC, phbasler commented on include/BSMPT/gravitational_waves/gw.h
> + * @return std::pair<double, int>
```suggestion
 * @brief returns the fluid velocity behind the wall, v−, and the expansion mode
 *
 * @param al \f$ \alpha \f$
 * @param vw \f$ v_w \f$
 * @param cs2b \f$ c_{s,b}^2 $ sound speed squared in the broken phase
 * @return std::pair<double, ExpansionMode>
```

2025-04-15 22:50 UTC, vollous commented on src/gravitational_waves/gw.cpp
>    if (epsturb_in == -1)
Those cases are caught by
```c++
if (UserDefined_epsturb != -1 and
    (UserDefined_epsturb < 0 or UserDefined_epsturb > 1))
{
  Logger::Write(LoggingLevel::Default, "Invalid choice for eps_turb.");
  return false;
}
  ```
in ```CalcGW.cpp```.

2025-04-16 06:50 UTC, vollous commented on include/BSMPT/bounce_solution/bounce_solution.h
> +  double I(const double &T);
Sounds good, fixed in PR.

2025-04-18 07:06 UTC, phbasler approved these changes

2025-04-18 07:06 UTC, merged